### ISSUE TITLE
how to build tesseract library?

### ISSUE THREAD

**Issue by BackT0TheFuture** [nguyenq/VietOCRwpf#1]
Hi,
would you like to tell me how to build tesseract library?
thx

**Comment by nguyenq** [comment]
Please consult https://github.com/charlesw or https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows.

**Comment by BackT0TheFuture** [comment]
I did follow the link you mentioned above，but got a lot dlls, not like yours, just libtesseract400.dll and liblept174.dll.
thx.

**Comment by nguyenq** [comment]
Check out Tess4 dev branch.

https://github.com/charlesw/tesseract/tree/feature/321-Tesseract-4
